server:
  port: 80
  tomcat:
    accesslog:
      buffered: true
      directory: E:/IDEAProject/lostandfound/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
  servlet:
    context-path: /
mybatis:
  mapper-locations: /mapper/**Mapper.xml
  type-aliases-package: com.jianghuling.lostandfound
spring:
  jackson:
    # get correct time
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://119.23.203.8:3306/shiwuzhaoling?characterEncoding=utf8
    username: iuser
    password: Iuser741@2019
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 30
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      maximum-pool-size: 15
      max-lifetime: 60000
  data:
    elasticsearch:
      cluster-nodes: 119.23.203.8:9300
      repositories:
        enabled: true

